### ISSUE TITLE
안녕하세요. 좋은 자료 감사합니다. 코드를 실행해보고 있는데 오류가 나는 것 같아 보고 드립니다.

### ISSUE THREAD

**Issue by mech12** [haven-jeon/KoGPT2-chatbot#5]
코랩에서 올려주신 코드를 실행중 맨 마지막 명령을 실행시 다음과 같이 오류가 발생하는 것 같습니다.
* 맨마지막 명령
> !CUDA_VISIBLE_DEVICES=0 python train_torch.py --gpus 1 --chat
* 에러메세지

```
2020-11-03 14:28:19.031157: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
INFO:root:Namespace(accelerator=None, accumulate_grad_batches=1, amp_backend='native', amp_level='O2', auto_lr_find=False, auto_scale_batch_size=False, auto_select_gpus=False, automatic_optimization=True, batch_size=96, benchmark=False, chat=True, check_val_every_n_epoch=1, checkpoint_callback=True, default_root_dir=None, deterministic=False, distributed_backend=None, fast_dev_run=False, flush_logs_every_n_steps=100, gpus=1, gradient_clip_val=0, limit_test_batches=1.0, limit_train_batches=1.0, limit_val_batches=1.0, log_every_n_steps=50, log_gpu_memory=None, logger=True, lr=5e-05, max_epochs=1000, max_len=32, max_steps=None, min_epochs=1, min_steps=None, model_params='model_chp/model_last.ckpt', num_nodes=1, num_processes=1, num_sanity_val_steps=2, overfit_batches=0.0, precision=32, prepare_data_per_node=True, process_position=0, profiler=None, progress_bar_refresh_rate=1, reload_dataloaders_every_epoch=False, replace_sampler_ddp=True, resume_from_checkpoint=None, sentiment='0', sync_batchnorm=False, terminate_on_nan=False, tpu_cores=<function _gpus_arg_default at 0x7f6c94292158>, track_grad_norm=-1, train=False, truncated_bptt_steps=None, val_check_interval=1.0, warmup_ratio=0.1, weights_save_path=None, weights_summary='top')
Traceback (most recent call last):
  File "train_torch.py", line 257, in <module>
    model = KoGPT2Chat.load_from_checkpoint(args.model_params)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/saving.py", line 132, in load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=lambda storage, loc: storage)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/cloud_io.py", line 31, in load
    with fs.open(path_or_url, "rb") as f:
  File "/usr/local/lib/python3.6/dist-packages/fsspec/spec.py", line 903, in open
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/fsspec/implementations/local.py", line 115, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fsspec/implementations/local.py", line 197, in __init__
    self._open()
  File "/usr/local/lib/python3.6/dist-packages/fsspec/implementations/local.py", line 202, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/content/KoGPT2-chatbot/model_chp/model_last.ckpt'


```

**Comment by haven-jeon** [comment]
모델 학습이 적절하게 진행되지 않아 model_last.ckpt가 생성되지 않을거 같습니다. 
파일이 있는지 확인해보시고 실행하시면 어떨까 합니다.

**Comment by mech12** [comment]
> 모델 학습이 적절하게 진행되지 않아 model_last.ckpt가 생성되지 않을거 같습니다.
> 파일이 있는지 확인해보시고 실행하시면 어떨까 합니다.

네. 모델파일이 생성되지 않았는데 제가 미쳐 파악을 못해 생긴 문제였더군요. 답변 감사합니다.
