### ISSUE TITLE
모델 학습 시 발생하는 오류에 대한 문의

### ISSUE THREAD

**Issue by waky80** [haven-jeon/KoGPT2-chatbot#6]
안녕하세요,
우선 좋은 자료 감사합니다.
해당 튜토리얼(pytorch)을 먼저 수행해보고 있는데요.
아래와 같은 오류가 발생했는데요.
해결 방법을 몰라서 문의합니다.

$ CUDA_VISIBLE_DEVICES=0 python3 train_torch.py --train --gpus 1 --max_epochs 2
INFO:root:Namespace(accelerator=None, accumulate_grad_batches=1, amp_backend='native', amp_level='O2', auto_lr_find=False, auto_scale_batch_size=False, auto_select_gpus=False, automatic_optimization=True, batch_size=96, benchmark=False, chat=False, check_val_every_n_epoch=1, checkpoint_callback=True, default_root_dir=None, deterministic=False, distributed_backend=None, fast_dev_run=False, flush_logs_every_n_steps=100, gpus=1, gradient_clip_val=0, limit_test_batches=1.0, limit_train_batches=1.0, limit_val_batches=1.0, log_every_n_steps=50, log_gpu_memory=None, logger=True, lr=5e-05, max_epochs=2, max_len=32, max_steps=None, min_epochs=1, min_steps=None, model_params='model_chp/model_last.ckpt', num_nodes=1, num_processes=1, num_sanity_val_steps=2, overfit_batches=0.0, precision=32, prepare_data_per_node=True, process_position=0, profiler=None, progress_bar_refresh_rate=1, reload_dataloaders_every_epoch=False, replace_sampler_ddp=True, resume_from_checkpoint=None, sentiment='0', sync_batchnorm=False, terminate_on_nan=False, tpu_cores=<function _gpus_arg_default at 0x7fe3531270d0>, track_grad_norm=-1, train=True, truncated_bptt_steps=None, val_check_interval=1.0, warmup_ratio=0.1, weights_save_path=None, weights_summary='top')
Traceback (most recent call last):
  File "train_torch.py", line 249, in <module>
    model = KoGPT2Chat(args)
  File "train_torch.py", line 125, in __init__
    self.tok_path = get_tokenizer()
  File "/usr/local/lib/python3.6/dist-packages/kogpt2/utils.py", line 68, in get_tokenizer
    cachedir=cachedir)
  File "/usr/local/lib/python3.6/dist-packages/kogpt2/utils.py", line 53, in download
    '.' * (50 - done)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-45: ordinal not in range(128)

감사합니다.

**Comment by waky80** [comment]
자체 해결 방법 공유합니다.

오류가 나는 "/usr/local/lib/python3.6/dist-packages/kogpt2/utils.py" 파일에서 52번 라인의 유니코드 문자인 '\u2588'을 다른 문자('=')로 바꾸니 해결되었습니다.
